name = "lexara-homepage"
main = "./dist/_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.dev]
name = "lexara-homepage-dev"
workers_dev = true
routes = [
  { pattern = "dev-www.lexara.app/*", zone_name = "lexara.app" }
]

# D1 Database for dev
[[env.dev.d1_databases]]
binding = "DB"
database_name = "lexara-auth"
database_id = "39dd504c-9bf8-44ff-86b0-d5c2c2b860a9"

# Staging environment
[env.staging]
name = "lexara-homepage-staging"
workers_dev = false
routes = [
  { pattern = "stage-www.lexara.app/*", zone_name = "lexara.app" }
]

# Production environment
[env.production]
name = "lexara-homepage"
workers_dev = false
routes = [
  { pattern = "lexara.app/*", zone_name = "lexara.app" },
  { pattern = "www.lexara.app/*", zone_name = "lexara.app" }
]

# Durable Objects - temporarily disabled
# [[durable_objects.bindings]]
# name = "FIRM_REGISTRY"
# class_name = "FirmRegistry"
# script_name = "lexara-homepage"

# [[migrations]]
# tag = "v1"
# new_classes = ["FirmRegistry"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "lexara-auth"
database_id = "39dd504c-9bf8-44ff-86b0-d5c2c2b860a9"

# Environment variables
[env.dev.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "info"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"