name = "engage-legal-ai"
main = "src/agent/main-worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Remove build step for now - using TypeScript directly

# Development environment
[env.dev]
name = "engage-legal-ai-dev"
workers_dev = false
route = { pattern = "dev.lexara.app/*", zone_name = "lexara.app" }

# Test/Staging environment  
[env.test]
name = "engage-legal-ai-test"
workers_dev = false
route = { pattern = "test.lexara.app/*", zone_name = "lexara.app" }

# Production environment
[env.production]
name = "engage-legal-ai-production" 
workers_dev = false
route = { pattern = "lexara.app/*", zone_name = "lexara.app" }

# Development environment bindings
[[env.dev.durable_objects.bindings]]
name = "CONVERSATION_SESSION"
class_name = "ConversationSession"
script_name = "engage-legal-ai-dev"

[[env.dev.durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-legal-ai-dev"

[[env.dev.vectorize]]
binding = "SUPPORTING_DOCUMENTS"
index_name = "supporting-documents-dev"

[[env.dev.vectorize]]
binding = "CONFLICT_DATABASE"
index_name = "conflict-database-dev"

[env.dev.ai]
binding = "AI"

# Test environment bindings
[[env.test.durable_objects.bindings]]
name = "CONVERSATION_SESSION"
class_name = "ConversationSession"
script_name = "engage-legal-ai-test"

[[env.test.durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-legal-ai-test"

[[env.test.vectorize]]
binding = "SUPPORTING_DOCUMENTS"
index_name = "supporting-documents-test"

[[env.test.vectorize]]
binding = "CONFLICT_DATABASE"
index_name = "conflict-database-test"

[env.test.ai]
binding = "AI"

# Production environment bindings
[[env.production.durable_objects.bindings]]
name = "CONVERSATION_SESSION"
class_name = "ConversationSession"
script_name = "engage-legal-ai-production"

[[env.production.durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-legal-ai-production"

[[env.production.vectorize]]
binding = "SUPPORTING_DOCUMENTS"
index_name = "supporting-documents"

[[env.production.vectorize]]
binding = "CONFLICT_DATABASE"
index_name = "conflict-database"

[env.production.ai]
binding = "AI"

# Durable Object migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ConversationSession"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["FirmRegistry"]

# Durable Objects bindings
[[durable_objects.bindings]]
name = "CONVERSATION_SESSION"
class_name = "ConversationSession"
script_name = "engage-legal-ai"

[[durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-legal-ai"


# Vectorize bindings for knowledge bases
[[vectorize]]
binding = "SUPPORTING_DOCUMENTS"
index_name = "supporting-documents"

[[vectorize]]
binding = "CONFLICT_DATABASE"
index_name = "conflict-database"

# Workers AI binding for Claude
[ai]
binding = "AI"

# Environment variables
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
# OpenTelemetry configuration
OTEL_EXPORTER_OTLP_PROTOCOL = "http/protobuf"
OTEL_SERVICE_NAME = "engage-legal-ai"
OTEL_SERVICE_VERSION = "0.1.0"

# Development-specific variables
[env.dev.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
API_BASE_URL = "https://api.dev.lexara.app"
ADMIN_BASE_URL = "https://admin.dev.lexara.app"
AUTH0_DOMAIN = "dev-sv0pf6cz2530xz0o.us.auth0.com"
AUTH0_CLIENT_ID = "OjsR6To3nDqYDLVHtRjDFpk7wRcCfrfi"
# OpenTelemetry configuration - dev
OTEL_EXPORTER_OTLP_ENDPOINT = "https://logfire-api.pydantic.dev"
OTEL_SERVICE_NAME = "engage-legal-ai-dev"

# Test/Staging-specific variables  
[env.test.vars]
ENVIRONMENT = "test"
LOG_LEVEL = "info"
API_BASE_URL = "https://api.test.lexara.app"
ADMIN_BASE_URL = "https://admin.test.lexara.app"
AUTH0_DOMAIN = "lexara-test.us.auth0.com"
AUTH0_CLIENT_ID = "test_client_id_placeholder"
# OpenTelemetry configuration - test
OTEL_EXPORTER_OTLP_ENDPOINT = "https://logfire-api.pydantic.dev"
OTEL_SERVICE_NAME = "engage-legal-ai-test"

# Production-specific variables
[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"
API_BASE_URL = "https://api.lexara.app"
ADMIN_BASE_URL = "https://admin.lexara.app"
AUTH0_DOMAIN = "lexara.us.auth0.com"
AUTH0_CLIENT_ID = "prod_client_id_placeholder"
# OpenTelemetry configuration - production
OTEL_EXPORTER_OTLP_ENDPOINT = "https://logfire-api.pydantic.dev"
OTEL_SERVICE_NAME = "engage-legal-ai-production"