#!/bin/bash

echo "Adding D1 binding to Cloudflare Pages project..."
echo ""
echo "Since wrangler doesn't support adding bindings to Pages projects via CLI yet,"
echo "you need to do this manually in the Cloudflare Dashboard:"
echo ""
echo "1. Go to https://dash.cloudflare.com"
echo "2. Select your account"
echo "3. Navigate to Workers & Pages > lexara-firm-portal-dev"
echo "4. Go to Settings > Functions > D1 database bindings"
echo "5. Add a binding:"
echo "   - Variable name: DB"
echo "   - D1 database: dev-lexara-firm-portal (c856a886-cf6b-421e-b24e-d24a441c0426)"
echo "6. Save the binding"
echo ""
echo "For environment variables, also add in Settings > Environment variables:"
echo "   - AUTH0_DOMAIN: dev-sv0pf6cz2530xz0o.us.auth0.com"
echo "   - AUTH0_CLIENT_ID: OjsR6To3nDqYDLVHtRjDFpk7wRcCfrfi"
echo "   - AUTH0_CLIENT_SECRET: (from .dev.vars)"
echo "   - AUTH0_MGMT_CLIENT_ID: 8joVG4YXDLZwpkwvaEyPJn8urP4oiTwM"
echo "   - AUTH0_MGMT_CLIENT_SECRET: (from .dev.vars)"
echo "   - JWT_SECRET: (generate a secure secret)"
echo ""
echo "After adding these, the deployment will automatically rebuild with the bindings."