# Wrangler configuration for Admin API Worker
name = "engage-admin-api"
main = "src/admin/admin-worker.ts"
compatibility_date = "2024-01-01"

# Worker configuration  
workers_dev = false
route = { pattern = "admin.lexara.app/*", zone_name = "lexara.app" }

# Environment variables
[env.dev]
name = "engage-admin-api-dev"
route = { pattern = "admin-dev.lexara.app/*", zone_name = "lexara.app" }

[env.dev.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
CORS_ORIGINS = "https://dev.lexara.app"
AUTH0_DOMAIN = "lexara-dev.us.auth0.com"
AUTH0_CLIENT_ID = "TO_BE_SET"
AUTH0_AUDIENCE = "https://api.dev.lexara.app"

[env.test] 
name = "engage-admin-api-test"
route = { pattern = "admin-test.lexara.app/*", zone_name = "lexara.app" }

[env.test.vars]
ENVIRONMENT = "test"
LOG_LEVEL = "info"
CORS_ORIGINS = "https://test.lexara.app"
AUTH0_DOMAIN = "lexara-test.us.auth0.com"
AUTH0_CLIENT_ID = "TO_BE_SET"
AUTH0_AUDIENCE = "https://api.test.lexara.app"

[env.production]
name = "engage-admin-api-production"
route = { pattern = "admin.lexara.app/*", zone_name = "lexara.app" }

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"
CORS_ORIGINS = "https://lexara.app"
AUTH0_DOMAIN = "lexara.us.auth0.com"
AUTH0_CLIENT_ID = "TO_BE_SET"
AUTH0_AUDIENCE = "https://api.lexara.app"

# Durable Object bindings
[[durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-firm-registry"

[[durable_objects.bindings]]
name = "CONVERSATION_SESSION" 
class_name = "ConversationSession"
script_name = "engage-main"

[[durable_objects.bindings]]
name = "USER_IDENTITY"
class_name = "UserIdentity" 
script_name = "engage-main"

# Vectorize bindings
[[vectorize]]
binding = "SUPPORTING_DOCUMENTS"
index_name = "supporting-documents"

[[vectorize]]
binding = "CONFLICT_DATABASE"
index_name = "conflict-database"

# KV bindings for session storage and caching
[[kv_namespaces]]
binding = "ADMIN_SESSIONS"
id = "admin_sessions_kv"
preview_id = "admin_sessions_kv_preview"

[[kv_namespaces]]
binding = "FIRM_CACHE"
id = "firm_cache_kv"
preview_id = "firm_cache_kv_preview"

# R2 bindings for file uploads
[[r2_buckets]]
binding = "ADMIN_UPLOADS"
bucket_name = "engage-admin-uploads"
preview_bucket_name = "engage-admin-uploads-preview"

# Analytics Engine binding for usage tracking
[[analytics_engine_datasets]]
binding = "ADMIN_ANALYTICS"
dataset = "admin_api_usage"

# Limits and performance (disabled for free plan)
# [limits]
# cpu_ms = 30000  # 30 seconds for complex admin operations

# Build configuration - skip for now
# [build]
# command = "npm run build:admin"
# cwd = "."
# watch_dir = "src"

# Rate limiting and security (applied to all environments)
[vars]
RATE_LIMIT_PER_MINUTE = "60"
MAX_REQUEST_SIZE = "10485760"  # 10MB for file uploads