# Wrangler configuration for Platform Admin Worker
name = "engage-platform-admin"
main = "src/platform/platform-worker.ts"
compatibility_date = "2024-01-01"

# Worker configuration  
workers_dev = false
route = { pattern = "platform.lexara.app/*", zone_name = "lexara.app" }

# Environment variables
[env.dev]
name = "engage-platform-admin-dev"
route = { pattern = "platform-dev.lexara.app/*", zone_name = "lexara.app" }

[env.dev.observability]
enabled = true
head_sampling_rate = 1

[[env.dev.durable_objects.bindings]]
name = "PLATFORM_SESSION"
class_name = "PlatformSession"
script_name = "engage-platform-admin-dev"

[[env.dev.durable_objects.bindings]]
name = "PLATFORM_AUDIT_LOG"
class_name = "PlatformAuditLog"
script_name = "engage-platform-admin-dev"

[[env.dev.durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-legal-ai-dev"

[env.dev.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
AUTH0_DOMAIN = "dev-sv0pf6cz2530xz0o.us.auth0.com"
AUTH0_CLIENT_ID = "QHexH0yTPx1xBZDIWrzltOjwGX86Bcx3"
AUTH0_CLIENT_SECRET = "2y6HD3Rc8tXD7XiMRojjjd6C4cKFw3m4g5tYkWYEdA_is3EmVv8qKQX1UDysQJPO"
AUTH0_AUDIENCE = "https://api.dev.lexara.app"
RATE_LIMIT_PER_MINUTE = "120"
MAX_REQUEST_SIZE = "5242880"

# KV bindings for dev environment (temporarily disabled for deployment)
# [[env.dev.kv_namespaces]]
# binding = "PLATFORM_SESSIONS"
# id = "platform_sessions_kv_dev"
# preview_id = "platform_sessions_kv_preview_dev"

# [[env.dev.kv_namespaces]]
# binding = "PLATFORM_CACHE"
# id = "platform_cache_kv_dev"
# preview_id = "platform_cache_kv_preview_dev"

# Analytics Engine binding for dev environment (temporarily disabled for deployment)
# [[env.dev.analytics_engine_datasets]]
# binding = "PLATFORM_ANALYTICS"
# dataset = "platform_admin_usage_dev"

[env.test] 
name = "engage-platform-admin-test"
route = { pattern = "platform-test.lexara.app/*", zone_name = "lexara.app" }

[[env.test.durable_objects.bindings]]
name = "PLATFORM_SESSION"
class_name = "PlatformSession"
script_name = "engage-platform-admin-test"

[[env.test.durable_objects.bindings]]
name = "PLATFORM_AUDIT_LOG"
class_name = "PlatformAuditLog"
script_name = "engage-platform-admin-test"

[[env.test.durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-legal-ai-test"

[env.test.vars]
ENVIRONMENT = "test"
LOG_LEVEL = "info"
AUTH0_DOMAIN = "lexara-test.us.auth0.com"
AUTH0_CLIENT_ID = "QHexH0yTPx1xBZDIWrzltOjwGX86Bcx3"
AUTH0_AUDIENCE = "https://api.test.lexara.app"
RATE_LIMIT_PER_MINUTE = "120"
MAX_REQUEST_SIZE = "5242880"

# KV bindings for test environment (temporarily disabled for deployment)
# [[env.test.kv_namespaces]]
# binding = "PLATFORM_SESSIONS"
# id = "platform_sessions_kv_test"
# preview_id = "platform_sessions_kv_preview_test"

# [[env.test.kv_namespaces]]
# binding = "PLATFORM_CACHE"
# id = "platform_cache_kv_test"
# preview_id = "platform_cache_kv_preview_test"

# Analytics Engine binding for test environment (temporarily disabled for deployment)
# [[env.test.analytics_engine_datasets]]
# binding = "PLATFORM_ANALYTICS"
# dataset = "platform_admin_usage_test"

[env.production]
name = "engage-platform-admin-production"
route = { pattern = "platform.lexara.app/*", zone_name = "lexara.app" }

[[env.production.durable_objects.bindings]]
name = "PLATFORM_SESSION"
class_name = "PlatformSession"
script_name = "engage-platform-admin-production"

[[env.production.durable_objects.bindings]]
name = "PLATFORM_AUDIT_LOG"
class_name = "PlatformAuditLog"
script_name = "engage-platform-admin-production"

[[env.production.durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-firm-registry"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"
AUTH0_DOMAIN = "lexara.us.auth0.com"
AUTH0_CLIENT_ID = "QHexH0yTPx1xBZDIWrzltOjwGX86Bcx3"
AUTH0_AUDIENCE = "https://api.lexara.app"
RATE_LIMIT_PER_MINUTE = "120"
MAX_REQUEST_SIZE = "5242880"

# KV bindings for production environment (temporarily disabled for deployment)
# [[env.production.kv_namespaces]]
# binding = "PLATFORM_SESSIONS"
# id = "platform_sessions_kv_production"
# preview_id = "platform_sessions_kv_preview_production"

# [[env.production.kv_namespaces]]
# binding = "PLATFORM_CACHE"
# id = "platform_cache_kv_production"
# preview_id = "platform_cache_kv_preview_production"

# Analytics Engine binding for production environment (temporarily disabled for deployment)
# [[env.production.analytics_engine_datasets]]
# binding = "PLATFORM_ANALYTICS"
# dataset = "platform_admin_usage_production"

# Durable Object bindings for platform admin
[[durable_objects.bindings]]
name = "PLATFORM_SESSION"
class_name = "PlatformSession"
script_name = "engage-platform-admin"

[[durable_objects.bindings]]
name = "PLATFORM_AUDIT_LOG"
class_name = "PlatformAuditLog"
script_name = "engage-platform-admin"

# Firm registry binding to manage firms
[[durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "engage-firm-registry"

# KV bindings for session storage and caching (temporarily disabled for deployment)
# [[kv_namespaces]]
# binding = "PLATFORM_SESSIONS"
# id = "platform_sessions_kv"
# preview_id = "platform_sessions_kv_preview"

# [[kv_namespaces]]
# binding = "PLATFORM_CACHE"
# id = "platform_cache_kv"
# preview_id = "platform_cache_kv_preview"

# Analytics Engine binding for platform metrics (temporarily disabled for deployment)
# [[analytics_engine_datasets]]
# binding = "PLATFORM_ANALYTICS"
# dataset = "platform_admin_usage"

# Rate limiting and security
[vars]
RATE_LIMIT_PER_MINUTE = "120"
MAX_REQUEST_SIZE = "5242880"  # 5MB