name = "lexara-firm-portal"
pages_build_output_dir = "./dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.dev]
name = "lexara-firm-portal-dev"

[env.dev.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
API_URL = "https://api-dev.lexara.app"

# Staging environment
[env.staging]
name = "lexara-firm-portal-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "info"

# Production environment
[env.production]
name = "lexara-firm-portal"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"