name = "engage-admin-api"
main = "src/api/admin/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Development settings
[env.development]
vars = { ENVIRONMENT = "development", LOG_LEVEL = "debug", ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:4321" }

# Production settings
[env.production]
vars = { ENVIRONMENT = "production", LOG_LEVEL = "info", ALLOWED_ORIGINS = "https://admin.engage.lexara.com,https://engage.lexara.com" }

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "engage-db"
database_id = "YOUR_D1_DATABASE_ID"

# Durable Objects binding
[[durable_objects.bindings]]
name = "CONVERSATION_SESSION"
class_name = "ConversationSession"
script_name = "engage-legal-ai"

# Vectorize bindings
[[vectorize]]
binding = "SUPPORTING_DOCUMENTS"
index_name = "supporting-documents"

[[vectorize]]
binding = "CONFLICT_DATABASE"
index_name = "conflict-database"

# R2 bucket for document storage
[[r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "engage-documents"

# Queue for DO->D1 sync
[[queues.producers]]
binding = "SYNC_QUEUE"
queue = "conversation-sync"

[[queues.consumers]]
queue = "conversation-sync"
max_batch_size = 10
max_batch_timeout = 30

# Routes
[env.production.routes]
pattern = "api.engage.lexara.com/*"
zone_name = "lexara.com"

[env.development.routes]
pattern = "localhost/*"

# Secrets (set via wrangler secret put)
# AUTH0_DOMAIN - Auth0 domain for JWT verification
# AUTH0_AUDIENCE - Auth0 API audience