name = "lexara-homepage"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Site configuration for serving static assets
[site]
bucket = "./dist"

# Development environment
[env.dev]
name = "lexara-homepage-dev"
workers_dev = true
routes = [
  { pattern = "dev-www.lexara.app/*", zone_name = "lexara.app" }
]

# Staging environment
[env.staging]
name = "lexara-homepage-staging"
workers_dev = false
routes = [
  { pattern = "stage-www.lexara.app/*", zone_name = "lexara.app" }
]

# Production environment
[env.production]
name = "lexara-homepage"
workers_dev = false
routes = [
  { pattern = "lexara.app/*", zone_name = "lexara.app" },
  { pattern = "www.lexara.app/*", zone_name = "lexara.app" }
]

# Environment variables
[env.dev.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
API_URL = "https://api-dev.lexara.app"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "info"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"