name = "engage-additional-goals-mcp"
main = "src/mcp/additional-goals/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.dev]
workers_dev = true

# Staging environment  
[env.staging]
name = "engage-additional-goals-mcp-staging"
workers_dev = false

# Production environment
[env.production]
name = "engage-additional-goals-mcp-production" 
workers_dev = false
routes = [
  { pattern = "additional-goals.engage.lexara.com/*", zone_name = "lexara.com" }
]

# Vectorize binding for supporting documents database
[[vectorize]]
binding = "SUPPORTING_DOCUMENTS"
index_name = "supporting-documents"

# Environment variables
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"

# Production-specific variables
[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"

# Staging-specific variables  
[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "debug"