name = "lexara-api-worker"
main = "dist/api-worker.js"
compatibility_date = "2024-12-01"

compatibility_flags = ["nodejs_compat"]

# Worker configuration
[build]
command = "pnpm run build"

# Durable Objects
[[durable_objects.bindings]]
name = "CONVERSATION_SESSION"
class_name = "ConversationSession"
script_name = "lexara-chat-interface"

[[durable_objects.bindings]]
name = "USER_IDENTITY"
class_name = "UserIdentity" 
script_name = "lexara-chat-interface"

[[durable_objects.bindings]]
name = "FIRM_REGISTRY"
class_name = "FirmRegistry"
script_name = "lexara-platform-admin"

# D1 Databases
[[d1_databases]]
binding = "FIRM_INDEX_DB"
database_name = "firm-indexes"
database_id = "placeholder-will-be-generated"

[[d1_databases]]
binding = "PLATFORM_DB"
database_name = "platform-data"
database_id = "placeholder-will-be-generated"

# Vectorize Indexes
[[vectorize]]
binding = "KNOWLEDGE_BASE"
index_name = "supporting-documents"

[[vectorize]]
binding = "CONFLICT_DB"
index_name = "conflict-database"

# KV Namespaces (for caching)
[[kv_namespaces]]
binding = "API_CACHE"
id = "placeholder-will-be-generated"

# Environment Variables
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
API_VERSION = "v1"

# Development Environment
[env.development]
name = "lexara-api-worker-dev"
route = "api-dev.lexara.app/*"

[env.development.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
CORS_ORIGINS = "https://dev.lexara.app,https://admin-dev.lexara.app,https://platform-dev.lexara.app"

# Staging Environment  
[env.staging]
name = "lexara-api-worker-staging"
route = "api-staging.lexara.app/*"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "info"
CORS_ORIGINS = "https://staging.lexara.app,https://admin-staging.lexara.app,https://platform-staging.lexara.app"

# Production Environment
[env.production]
name = "lexara-api-worker"
route = "api.lexara.app/*"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"
CORS_ORIGINS = "https://lexara.app,https://admin.lexara.app,https://platform.lexara.app"

# Limits and Performance
[limits]
cpu_ms = 30000
memory_mb = 128

# Observability
[observability]
enabled = true